### PR TITLE
Use luaossl instead of luacrypto.

### PR DESCRIPTION
**Pull request by saucisson**
The `luacrypto` module does not seem to be maintained anymore (mkottman/luacrypto#39). Its current version on luarocks does not accept Lua 5.3, which is annoying.
This pull request is a proposal to use `luaossl` instead, as it is compatible with newer version of Lua.

**Warning:** i am a totally newbie in openssl, so the proposed fixes might be totally wrong. I just checked that all tests still pass. Moreover, the `luaossl` module can throw errors. I did not add code to catch them.

### CODE REVIEW

**Comment by DorianGray** [comment]
We need to catch the errors at least on decode and return them as nil, message to match the rest of the behavior(to avoid users from having to add pcalls everywhere). More tests on this behavior would be ideal.

Unfortunately, I can't accept this pull request until luaossl makes it onto luarocks =(

**Comment by saucisson** [comment]
From [`luaossl` documentation](http://25thandclement.com/~william/projects/luaossl.pdf), neither `hmac.*` functions nor `digest.*` ones throw errors.
But the `pkey.*` functions can throw. They are now wrapped within `pcall`s, and two tests have been added to check this behavior. Note that there is still an `error` thrown when the signature cannot be generated.

**Comment by DorianGray** [comment]
Awesome, I'm going to test this with a few of my projects to make sure it doesn't fail in weird ways and then merge. This looks great, thanks!

**Comment by saucisson** [comment]
It can cause problems to you and other people using `pkey`s instead of text keys, as they are expected to be instances of `openssl.key` in this branch, and `crypto.pkey` in master.
An easy to fix this is to use `crypto` to dump keys and give them back to `openssl`. It is implemented in the latest commits, and tests using `luacrypto` keys have been added back.

**Comment by DorianGray** [comment]
Hmm, if we're going to break compatibility anyways, we should make the interface accept string keys instead of pkey objects. Hide the implementation details from the user. I'll do that unless you get there first.

**Comment by saucisson** [comment]
I have updated the code and tests to only accept strings for keys. An assertion throws an error in case a pkey (from `luacrypto` or `luaossl`) is used, as it is an invalid use of the library.

**Comment by DorianGray** [comment]
Thanks! That looks really good.

**Pull request merged**
